const adjectives = {
    flaws: [
        [" ", "Childish", "Fickle", "Foolhardy", "Graceless", "Hesitant", "Impulsive", "Inexperienced", "Scornful", "Unlucky"],
         [" ", "Aloof", "Cynical", "Gloomy", "Laid-Back", "Nervous", "Quarrelsome", "Shallow", "Uptight", "Weary"],
         [" ", "Arrogant", "Forgetful", "Literal-Minded", "Misinformed", "Naïve", "Obtuse", "Predictable", "Presumptuous", "Witless"]
     ],
    talents: [
        [" ", "Cautious", "Determined", "Long-Suffering", "Lucky", "Nimble", "Punctilious", "Resourceful", "Sensible", "Talented"], 
        [" ", "Charming", "Cheerful", "Confident", "Hot-Blooded", "Intense", "Melodramatic", "Pushy", "Romantic", "Sincere"],
        [" ", "Calculating", "Imaginative", "Meddlesome", "Perceptive", "Scheming", "Skeptical", "Thoughtful", "Tricksy", "Well-Read"]
    ]
}

const traits = {
    " ": {text: "[Select a trait from the dropdown]"},
    "Amphibious": {text:"You can move and breathe underwater as easily as on land. Fins, scales, and a conspicuous fishy smell are customary but not obligatory.", effort: "expel a gout of pressurised water out to Near range."},
    "Bottomless Belly": {text:"You can safely swallow anything you can fit in your mouth, and digest anything you can swallow, or simply hold onto it to spit back up later. You receive one extra inventory slot for this purpose. Digesting things that aren't food usually doesn't allow you to clear Stress; the GM will inform you of any exceptions.", effort: "swallow an object up to your own size and store it in your internal inventory slot; holding onto it isn't effortful, but retrieving it again is."},
    "Bulging Brain": {text:"You enjoy an excess of brain matter; this might result in a notably bulbous head, or you may keep it somewhere less conventional. You can project your thoughts to others and read their surface thoughts in turn, both out to Near range.", effort: "mentally contact anyone whose true name you know, regardless of range."},
    "Cunning Crafter": {text:"Your flesh resonates with a particular natural material [roll or choose which]. You can work it without tools, shape it like soft clay, and cause small objects made of it to leap to your hand from Touch range.", options: ["Metal", "Stone", "Wood"], effort: "call an appropriate object to your hand from Near range instead."},
    "Curative Corpus": {text:"Some part of your body is edible. Perhaps your plant-like physiology produces tasty fruit, or perhaps the ichor in your veins can be tapped as a restorative elixir. When you choose your starting inventory, you gain 5 Stress worth of food, which doesn't occupy an inventory slot; you can't eat this food to clear Stress, but others can. You can consume other food to replenish your supply on a one-for-one basis. Resting resets your supply to 5 points.", effort: "mark 1–5 Stress to increase your food supply by an equal amount; you may not cause yourself to Stress Out in this way."},
    "Deep Digger": {text:"You have some feature which allows you to rapidly move through earth; this might represent great shovel-like paws, or a secretion which dissolves soil. You require no tools to dig, and can do so at ten times the usual rate.", effort: "burrow through earth as quickly as you could run, collapsing your tunnel behind you."},
    "Defensive Dermis": {text:"Your body has a protective coating that makes you difficult to harm. You might have sharp spines or a crustacean-like shell, or you might simply be so slippery that it's impossible to get a grip on you. [Roll or choose to specify]", options: ["Crusty", "Prickly", "Slippery"]},
    "Dexterous Digits": {text:"Your manipulators are capable of astounding feats of craft and legerdemain. This customarily takes the form of very long fingers with too many joints, though other forms are possible."},
    "Dizzying Display": {text:"Your body can produce a disorienting sensory display. You might be luminous in the manner of certain sea creatures, or exude an unfathomable stench [Roll or choose what sense your display assaults]. You can adjust the quality and intensity of this display at will, or wield it to stun or disorient all creatures within Touch range.", options:  ["Loud display", "Luminous display", "Stinky display"], effort: "emit a burst which stuns or disorients all creatures within Near range; this Trait is then disabled and can't be tagged or otherwise employed for a few minutes."},
    "Extra Organs": {text:"Your body is crowded with supernumerary organs – two hearts, three lungs, glands with no human analogue, etc. You have limitless endurance, and whenever you encounter a harmful environment (e.g., extreme heat, poison gas, the vacuum of space, and so forth), you can make up an organ on the spot which renders you immune to it. This might represent spontaneously developing an adaptation to the harmful enviroment, or revealing the existence of an organ you've had all along – the effect is the same either way."},
    "Fast Feet": {text:"You're capable of an unlikely turn of speed. You might stride on a pair of improbably long legs (which double your height but don't increase your weight), or scramble low to the ground on countless tiny feet, or perhaps you have wheels. Your running speed is tripled.", effort: "sprint across a body of water or some other surface that really oughtn't support you – which it won't, if you stop."},
    "Firm Flesh": {text:"Your flesh is as dense as stone or iron, which you may in fact be made of. Multiply your weight by five.", effort: "hold so perfectly still that you could be mistaken for a statue; while in this state, you need not eat, drink or breathe."},
    "Flowing Form": {text:"It's unclear whether you have bones. You can make small adjustments to your bodily proportions at will; this includes rough changes to your overall appearance, though you can't add or remove features, nor alter the colour or texture of existing ones.", effort: "squeeze yourself through any gap that's at least a finger's-breadth wide."},
    "Fluttering Flight": {text:"You can fly short distances. This ability could stem from a number of features; for example, you might have short, stubby wings, or make gliding leaps, or you might inflate your body with air and float like a balloon.", effort: "hover in place, fly straight up, or perform other improbable aerobatics appropriate to your method of flight."},
    "Fulsome Fluids": {text:"One of your fluids has an unusual feature [roll or choose which feature], and you can produce it in quantity. (By default it's your spit; alternatives should respect your group's comfort level.)", options: ["Adhesive", "Corrosive", "Slippery"], effort: "produce enough fluid to soak everything in Touch range or a single target out to Near range."},
    "Hundred-handed": {text:"Your complement of manipulators isn't terribly well defined. You always have at least four hands (or equivalent members), and the exact number can vary at need.", effort: "have as many hands as you need to have."},
    "Langorous Lure": {text:"You have some arresting feature – perhaps shimmering fur, glowing eyes, a polyphonic singing voice, or an anglerfish-like lure – that's unnaturally good at capturing people's attention. You can use it to beckon or distract other creatures out to Near range.", effort: "induce a suggestible state in a single creature within Touch range; this is parlour-trick hypnosis, not magical mind control, so you can't compel a creature to do anything they'd find strongly objectionable, and a creature with a Stress Limit must be Stressed Out first."},
    "Lanky Limbs": {text:"You have extraordinary reach. You might sport unfolding, many-jointed arms, stretchy tentacles, prehensile hair, or even a truly prodigious tongue. In any case, your Touch range is tripled.", effort: "strike or grab something within Near range; if whatever you grab is bigger than you, you can swing from it or fling yourself toward it."},
    "Masterful Mimic": {text:"Your vocal apparatus can replicate any sound you've ever heard, up to the volume of a grown human shouting (or perhaps louder, if another Trait permits it).", effort: "mimic the voice of a specific person so exactly that even their own loved ones can't tell the difference."},
    "Menacing Missiles": {text:"You can produce some sort of harmful projectile. You might hurl crystal spines with a flick of your tail, spit up stones with your cannon-like proboscis, or simply fling whatever comes to hand with deadly force and accuracy. In any case, you enjoy effectively unlimited ammunition and can strike out to Near range.", effort: "pepper a group of closely spaced targets within Near range with rapid-fire projectiles, or spend a few moments carefully taking aim and make a single strike out to Far range."},
    "Mighty Muscles": {text:"You're much stronger than your size would suggest. You might have bulging thews, or your appearance may belie nothing of your strength. You can lift ten times your own weight, and contend on even footing with creatures ten times your size. (A hundred times in both cases if you're Puny.)", effort: "increase your lifting capacity to a hundred times your own weight (or a thousand times if you're Puny)."},
    "Modal Morphology": {text:"You can assume an alternate form, with effort. Perhaps you become a particular animal, or perhaps you have an alter ego which reshapes your body when it emerges. Your alternate form affects your Traits—each of your forms has this Trait and two others—and may also rearrange your Facets [roll or choose how].", options: ["no Facet change", "swap Ethos/Pathos", "swap Ethos/Logos", "swap Pathos/Logos"], effort: "mark 1 Stress and assume your alternate form, or 2 Stress if your transformation alters your Facets. This action need not be sustained, but you must repeat it to change back."},
    "Polycephalous": {text:"You're literally two-faced. You might have a talkative symbiote, a second face on your chest that gives voice to another side of your personality, or two entirely separate heads; in any case, you (the player) portray both faces. This Trait doesn't let you act more often than other God-eaters, but it may allow you to attempt things that would usually require two people.", effort: "offer yourself helpful advice or watch your own back, improving a test's Calamity Threshold by 1 – for example, from 9+ to 10+."},
    "Primordial Power": {text:"Your body can channel one of the primordial elements [roll or choose which one], typically via a specialised organ, though you might also breathe it, or simply radiate an aura. You can produce harmless displays of your element which can be felt out to Near range, or direct concentrated bursts to stun or wound a single creature within Touch range.", options: ["cold", "fire", "lightning", "acid", "wind", "water"], effort: "produce a concentrated burst which affects all creatures in Touch range or a single target out to Near range."},
    "Prismatic Pelt": {text:"Your skin (feathers, fur, scales, etc.) can change colour rapidly, and often does so unconsciously in response to your moods. You can adopt simple patterns, including camouflage, or simply change colours to express yourself.", effort: "mimic your surroundings so exactly that you can hide in plain sight, even while being observed."},
    "Roving Members": {text:"You can detach (and re-attach) your body parts and act through them at a distance. For example, an eye can see, a hand can crawl and grab, etc. Your detached members use your Facets when making tests, and may have access to your other Traits if appropriate. You can have multiple members deployed at once, though you can only act through one at a time. Mark 1d6 Stress if a detached member is destroyed.", effort: "regrow a lost member over the course of a few minutes; if the missing part wasn't destroyed, the old one dies as soon as you start growing a new one."},
    "Sticky Steps": {text:"You can cling to any surface, allowing you to scutter up walls and across ceilings. You might have insectile limbs or chameleon-like finger pads, or you may exude a gluey mucus.", effort: "become immovable – whatever you're clinging to will give out before your grip does."},
    "Striking Mien": {text:"Something about your appearance [roll or choose what] conveys an impression that transcends language.", 
    options: ["Annoying", "Dignified", "Piteous", "Predatory", "Spooky", "Trustworthy"], 
    effort: "intensify your mien into a psychic attack on a single creature within Near range; for example, if you're Dignified, the weight of your disapproval can be almost literally crushing."},
    "Superior Sense": {text:"Some of your senses [roll or choose which] are vastly more acute than a human's. Superior senses other than sight also become at least as discerning as a human's vision. Your sense organs are exaggerated in some way; for example, if your superior sense is “Hearing and Touch”, you might have huge ears and long whiskers.", options: ["Hearing and Touch" ,"Sight", "Taste and Smell"], effort: "examine something with your superior sense as though it was one Range band closer (e.g., Far to Near, etc.)."},
    "Undercooked": {text:"You came out of the pot a little underdone – not just physically, but existentially. People have a hard time describing what you look like, and their eyes tend to slide right past you unless they have a specific reason to pay attention to you. People who know your true name are immune to the latter effect and can notice and identify you normally (though they still have trouble describing you)."},
    "Unusual Sense": {text:"You have a sense normally found in animals [roll or choose which]; for example, you might echolocate like a bat, detect heat like a snake, or perceive electrical fields – including the fields produced by living creatures' nervous systems – like a platypus.", options: ["Echolocation", "Electroreception", "Thermal Vision"]},
    "Unusual Size": {text:"You're either unusually large or unusually small [roll or choose which]. If you're Hulking, multiply your weight and lifting capacity by ten and your height by two. If you're Puny, divide your weight by ten and your height by two, but don't reduce your lifting capacity – you're very strong for your size.", options: ["Hulking", "Puny"]},
    "Vile Venom": {text:"Your body produces an injected venom [roll or choose its effect]. This Trait comes with a suitable method of delivery if you don't already have one; perhaps you have small claws or a retractable stinger, or perhaps you lick a bladed weapon to envenom it.", options: ["Hallucinogenic", "Necrotic", "Sedative"]},
    "Weaving Webs": {text:"You can produce a sturdy thread – perhaps drawing it from spider-like spinnerets, or spinning it like yarn from your hair or beard. This thread can be sticky or not, at your discretion, and will support up to ten times your weight.", effort: "rapidly produce a mass of threads which entangle everything within Touch range (excluding yourself) or a single target within Near range."},
    "Wicked Weapon": {text:"Your body possesses imposing natural armaments, and you always count as armed with a deadly weapon [roll or choose its effect]. You might have great sharp teeth, iron-hard hooves, or something more outlandish.", options: ["Cutting", "Piercing", "Smashing"], effort: "cut, pierce or smash any physical object, no matter what it's made of; this doesn't increase the size of the chunk you destroy, so – for example – chewing through a concrete wall may take some time, but its material is no obstacle."}
}
const features = [" ",
    "antennae/whiskers",
    "antlers/horns",
    "beak/mandibles",
    "big ears/eyes",
    "bony/woody shell",
    "bright colours",
    "claws/pincers",
    "clockwork innards",
    "crest/mane",
    "crystalline nodes",
    "deep/gravelly voice",
    "distinctive smell",
    "feathers/leaves",
    "feelers/tentacles",
    "fins/frills",
    "fur/moss",
    "geometric markings",
    "huge/tiny head",
    "iridescent/metallic",
    "large/toothy mouth",
    "long/no neck",
    "long hair/beard",
    "lopsided anatomy",
    "many/compound eyes",
    "moist/oozy",
    "mushroomy growths",
    "noisy metabolism",
    "plated/segmented",
    "pockmarked/scarred",
    "prehensile tongue",
    "prominent tail",
    "ridges/scales",
    "snout/trunk",
    "translucent flesh",
    "hot/cold skin",
    "vaporous aura"]
    
const creeds = {
        " " : "Select your creed from the dropdown or write your own...", 
        "Durden" : "Honestly, you're just looking for a good fight, and you've never been one to set your sights low – you leave the deep philosophising to your more cerebral peers. Your Rebellious Arts are ways of doing violence to reality itself.", 
        "Locksley" : "The universe hangs in balance between Order and Chaos; your allegiance lies with the latter. Your Rebellious Arts spring from the insight that the laws of God and the laws of man have much in common: it's only a crime if you get caught.", 
        "Marcus Junius" : "You walk the God-eater's path with perfect literalism: God is a tyrant, and you intend to find Him, kill Him, and eat Him. Your Rebellious Arts are acts of pure contrarian refusal to conform; you don't care why they work, only that they work.", 
        "Morpheus" : "There's something wrong with the cosmos on a fundamental level, and the culmination of that disorder is what we call “God”. Your Rebellious Arts are intuitive exploits of the universe's flawed structure.", 
        "Powell" : "Eating God is a metaphor for dismantling structural inequalities and throwing down systems of oppression. Your Rebellious Arts are intellectual exercises; you likely have abstruse quasiscientific explanations for how they operate.",  
        "Theophagus": "The consumption of godly flesh is an act of worship in many faiths – you simply take it further than most would consider strictly appropriate. Your Rebellious Arts are drawn from scraps of divinity you've already digested."}
        
const rebelliousArts = {
    " " : "[Select an Art from the dropdown]" , 
    "Alteration" : "You refute the lie of form. When you activate this Art, you transform into any inanimate object that's between one-tenth and ten times your own mass. While you sustain this Art, your transformation is fully functional and stands up to even the most detailed examination. You retain the ability to move and act as you normally could while transformed; however, you're forced to resume your true form – ending the Art – if someone who knows or suspects that you're not what you seem verbally calls you out, so discretion is advised. The Art also ends if someone tries to remove any significant part of your assumed form." , 
    "Ascension" : "You refute the lie of gravity. For as long as this Art is sustained, you may reorient the direction of gravity, with respect to yourself only, at will; for example, you might choose to fall upward instead of down, or walk on a wall as though it were a floor. Whatever you're wearing and carrying is also affected, though if the total weight of your worn and carried objects ever exceeds your own weight, normal gravity immediately reasserts itself. This Art may not vary the strength of your personal gravity – only its direction – and should be practiced with caution when outdoors." , "Autonomy" : "You refute the lie of boundaries. While you sustain this Art, you may freely bypass obstacles to your freedom of movement, without making tests or incurring Stress. You can pass though hazardous terrain and inclement weather without harm or hinderance; you can't be physically restrained unless you allow it (and you may escape any existing restraints simply by choosing to do so); and barred portals of all kinds – locked doors, magical force fields, etc. – spring open at your touch. This Art doesn't grant any movement capabilities you don't already possess, nor will it create egress where none exists; however, if an effortful application of one of your Traits would allow you to destroy or bypass a barrier, you may do so without interrupting this Art. This is an exception to the usual restriction on performing an effortful action while already sustaining one." , 
    "Consumption" : "You refute the lie of limitations. When you activate this Art, you can perform one notionally impossible act of consumption, like silencing a speaker by eating their words, slurping the colour out of a painting, or devouring someone's shadow. The phenomenon to be eaten must fit within Near range of you, though you can eat a part of a larger phenomenon. A creature must have no Stress Limit or currently be Stressed Out in order to be devoured. This Art need be sustained only for as long as it takes to perform the act of consumption; anything that's eaten remains eaten once it ends. Persistently impossible effects (e.g., having no shadow) correct themselves after a few hours." , 
    "Conveyance" : "You refute the lie of location. While unobserved – even momentarily – you can vanish from your current location and appear in any other unobserved location within Near range. You don't need line of sight to your destination – if you mistakenly try to move to a nonexistent location, the Art simply doesn't activate. Vanishing in this way obscures physical evidence that you were ever present in your former location; the consequences of your actions remain, but it becomes impossible to provably connect them with you. This Art may be sustained to perform repeated vanishing acts in quick succession without paying separately for each one, provided that no more than seven heartbeats pass between vanishings." , 
    "Emulation" : "You refute the lie of constancy. When you activate this Art, choose one Trait of a creature, object or location within Touch range. While you sustain this Art, you gain a copy of that Trait as your own; discuss with the GM what change or mark this produces in you. If this Art's target has a Stress Limit, you must personally have caused it to suffer at least one point of Stress in the past few minutes to emulate its Traits, though it doesn't matter how – humiliation is as good as injury for this purpose. You may make effortful use of the emulated Trait while sustaining this Art; this is an exception to the normal limit on effortful actions." , 
    "Exposition" : "You refute the lie of omission. When you activate this Art, in no more than seven words, introduce a physical feature of your current location. This feature must fit within Near range of you, may not contradict any fact about your location that's already been established, and may not place any character in immediate danger unless they have no Stress Limit or are currently Stressed Out; apart from these restrictions, the feature's presence need not be plausible. The described feature proves to be present, as though it had simply gone unmentioned until that moment. It persists for as long as you sustain this Art. Afterward, it's liable to quietly vanish when no-one is looking; the timing of its disappearance is, however, entirely at the GM's discretion." , 
    "Guising" : "You refute the lie of identity. When you activate this Art, describe a social role in no more than seven words: ‘local farmer’, ‘off-duty librarian’, ‘cultist of the Red God’, etc. While you sustain this Art and behave in a manner that's consistent with your role, anyone who doesn't know your true name will accept you as such, regardless of your appearance. This Art can't be used to impersonate specific people, though a role held by a specific person is fair game; e.g., ‘the king of the realm’ is valid, but ‘King Reginald III’ is not. Affected characters aren't compelled to react in any particular way – they'll respond as they normally would to encountering a person of your assumed role." , 
    "Iteration" : "You refute the lie of linear time. This Art can be activated immediately after seeing the outcome of one of your own tests. When you do, you retroactively roll an additional die on that test, just as though you'd spent Obstinacy to add a die in the first place. This Art obeys the usual restrictions on enhancing tests, so you can't use it on a test that you already spent Obstinacy on (including tests on which you've already claimed an extra die by rolling in conjunction with another Art). If rolling the extra die changes the test's outcome, observers will remember both the original result and the new one. This Art need not be sustained." , 
    "Keeping" : "You refute the lie of dimensionality. When you activate this Art, you can stash anything within Touch range in one of your open inventory slots. The article to be stashed must be a single discrete object or a collection of similar objects or substances (e.g., sand, water, etc.), and must fit within Near range of you; a creature must consent, have no Stress Limit, or currently be Stressed Out in order to be stashed. Later, you can reach into any closed container – including your own mouth – and retrieve the stashed article, or allow another character within Near range to do the same; the container is not harmed by this. This Art need not be sustained, but you can only stash one article per activation." , 
    "Making" : "You refute the lie of division between will and action. This Art speeds your progress at any creative or reparative task: crafting, cooking, cleaning, etc. The work of hours is accomplished instantly, in a frantic blur of activity; for greater tasks, you can sustain this Art to improve your pace by ten thousand times, though the Obstinacy cost must be paid once per minute, with each minute accomplishing a week of labour. This Art does not elide the need for tools or materials – it merely speeds the work." , 
    "Miscellany" : "You refute the lie of possession. When you activate this Art, choose any item you could place in your inventory that's been within Near range and line of sight of you in the past day. That item appears in one of your open inventory slots. This Art cannot target items that are being held by another character, unless that character has no Stress Limit or is currently Stressed Out, but items which are merely worn or carried are fair game. If it's unclear whether you've encountered a desired item in the past day or not, assume the anwer is ‘yes’ if it would have been a permissible starting inventory choice for you, and ‘no’ otherwise. This Art need not be sustained." , 
    "Multiplicity" : "You refute the lie of singularity. When you activate this Art, roll 2d6; that many additional copies of you appear within Near range. This Art doesn't let you act more often than other players, and all instances of you share a single Stress total and a single Obstinacy pool; its principal benefit is that it lets you perform actions that would usually require a group or oblige you to be in several places at once. You may re-activate this Art while sustaining it in order to increase the number of instances of you by another 1d6; this is an exception to the usual restriction on performing an effortful action while already sustaining one." , 
    "Negation" : "You refute the lie of cause and effect. Any time you'd mark Stress, you may activate this Art to negate both the Stress and the narrative circumstance that caused it. How this occurs is chosen by the GM, and may be inexplicable to observers. For example, if hurled from a cliff, you might hang in the air in defiance of gravity; if crushed by an enemy's club, you might turn out to have been standing behind the club's wielder. If a circumstance inflicts a variable amount of Stress, you can roll the Stress die before deciding whether to activate this Art. The Art must be sustained if the circumstance you're negating is an ongoing condition (e.g., failing to fall in spite of there being no ground beneath you); if the circumstance that would have caused you to mark Stress affects multiple characters, it's negated for you only." , 
    "Realisation" : "You refute the lie of perception. For as long as this Art is sustained, you may interact with visual depictions of unreal objects as though they were real. For example, you might snatch a sword from a statue's hand, or pass through a drawing of a door chalked upon a wall to reach the other side. You may use this Art on depictions you created yourself, but creating them is usually an effortful action, so you can't do so while also sustaining the Art; if doing so requires a test, you can wait and see the outcome of that test before deciding whether to activate this Art." , 
    "Revelation" : "You refute the lie of objective truth. When you activate this Art, you can make a statement of up to seven words: everyone who hears you will be certain that you're lying. This Art perfectly defeats both mundane intuition and magical senses. However, it has two limitations. First, affected characters are not obliged to believe the exact opposite of what you said, nor do you get to choose what they decide the real truth is. Second, if you make an obviously true statement, they'll come to their senses the moment you stop sustaining this Art. In any case, while the Art is sustained, no evidence will persuade affected characters that your statement was truthful; once you stop sustaining it, the effect may linger, but can be overcome by mundane persuasion." , 
    "Ubiquity" : "You refute the lie of separation. For as long as this Art is sustained, you may act upon creatures and objects at Near or Far range as though you were at Touch range. You may act at Near range in this way as you wish; doing so at Far range causes the Art to end once that action is complete. Acting at a distance in this way doesn't cause you to move, but you suffer the consequences of your actions (marking Stress, etc.) as though you were actually within Touch range of whatever you acted upon. The GM is free to invent an explanation for this, but isn't obligated to do so." , 
    "Utility" : "You refute the lie of purpose. When you activate this Art, you can grab any object or creature you can lift with one hand; if you grab a creature, it must consent, have no Stress Limit, or currently be Stresed Out in order to be affected. For as long as you sustain this Art, you can use the target as a perfectly suited tool for any task, provided a hand-held tool for that task could plausibly exist. You may use the target in any number of ways; it will prove to be perfectly suited for each new task you set it to. The target is not harmed or permanently altered by being used in this way. You can set the target down without terminating this Art, but if another creature picks it up, the effect ends."}
    
const food = ["a bag of candy",
"a big cube of tofu",
"a bottle of fine wine",
"a canned rations",
"a string of dry-cured sausages",
"a hunk of dubious meat",
"a box of elaborate pastries",
"a large sandwich",
"a loaf of bread",
"mysterious gooey foodstuff",
"a powerful cheese",
"a jug of stew",
"a single enormous egg",
"a sack of fried bugs",
"an unseasonal fruit basket",
"vermin on a stick™",
"a whole cabbage"]

const tools = ["a ball of yarn",
"a bar of soap",
"a begging bowl",
"a big knife",
"a bone hair-brush",
"a book of poetry",
"a brass lantern",
"a broken sword",
"a burlap sack",
"a chainmail vest",
"a coil of silk rope",
"a coloured chalk",
"a dozen candles",
"an empty glass bottle",
"an engraved lodestone",
"a fancy hat",
"a gilded chalice",
"a gnarled wooden club",
"a handful of gold coins",
"an indecipherable scroll",
"a live rat",
"a large rock",
"a long poking-stick",
"an oversize boot for each of your feet",
"a paint-pot and brush",
"a poorly tuned lute",
"a pot-lid shield",
"a rolled-up blanket",
"a rusty fork",
"a sack of marbles",
"a sharp-bladed shovel",
"a silver pocketwatch",
"a sturdy umbrella",
"a thick woolen sock for each of your feet",
"tinted eyeglasses",
"a well-worn broom"]
				
